//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvuyelwafitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ADDRESS_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string Street_add { get; set; }
        public string Town_City { get; set; }
        public string Province { get; set; }
        public string Zip { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
