//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvuyelwafitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Item
    {
        public int CART_ITEM_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string PROD_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
