//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvuyelwafitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ORDER_NUM { get; set; }
        public int CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int STATUS_ID { get; set; }
        public int DEL_STATUS_ID { get; set; }
        public Nullable<int> SESSION_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment_Statuses Payment_Statuses { get; set; }
        public virtual Delivery_Status Delivery_Status { get; set; }
    }
}
